spring:
  application:
    name: EurekaServer

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 35000
    instance:
      health-check-url-path: /health
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 35

logging:
  level:
    org.springframework.cloud.netflix.eureka.registry: DEBUG
    org.springframework.cloud.netflix.eureka.health: DEBUG